server:
  port: 8085

spring:
  application:
    name: ms-spring-webflux-nosql
  data:
    mongodb:
     uri: mongodb+srv://luisrivas:Alexander1903@cluster0.gr4avuk.mongodb.net/32_luis_rivas?retryWrites=true&w=majority

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html